accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),  # register는 함수형 뷰
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 루트로 요청했을때 photo.urls.py로 연결된다.
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
]

# static매서드를 통해 media_url에 해당하는 주소를 가진 요청에 대해서는 media_root로 찾아가 응답하도록 로직 구현
# 아래 로직은 config/settings.py > DEBUG 모드가 True일때만 동작한다.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo


# 네임스페이스를 지정하기위해 app_name 사용
# app_name을 지정했다면 템플릿 url을 등록할때 photo_를 뺀 나머지 name값을 지정하면 된다.
# <a href="{% url 'photo:photo_upload' %} class="nav-link">Upload</a>
app_name = 'photo'

urlpatterns = [
    # 루트로 요청 : 함수형 뷰 photo_list를 통해 응답, 함수형 뷰 이기 때문에 .as_view() 메서드를 붙이지 않는다.
    path('', photo_list, name='photo_list'),
    # detail/id 로 요청 : DatailView 클래스형 뷰를 통해 응답
    # 사용할 model지정, 템플릿 지정
    path('detail/<int:pk>', DetailView.as_view(model=Photo,
                                               template_name='photo/detail.html'), name='photo_detail'),
    # upload로 요청 : PhotoUploadView로 응답
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    # delete, update 요청 : Pk id 값으로 접속하여 해당 데이터를 수정, 삭제 한다.
    path('delete/<int:pk>', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>', PhotoUpdateView.as_view(), name='photo_update'),
]

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Photo(models.Model):
    # author 는 User 테이블과 포린키 관계를 둔다. User테이블의 데이터가 삭제될경우 옵션으로 on_delete를 CASCADE로 설정하였다.
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_photos')
    # 업로드 되는 파일은 photos폴더에 년/월/일 하위에 업로드 된다. 이미지가없다면 기본 이미지로 데이터베이스에 저장된다.
    photo = models.ImageField(
        upload_to='photos/%y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # 옵션 클래스인 Meta 클래스를 작성하여 순번옵션을 설정한다.
    class Meta:
        ordering = ['-updated']

    # get_absolute_url은 상세페이지의 주소를 반환하는 메서드를 작성했다.
    def get_absolute_url(self):
        # reverse는 url패턴을 통해 해당 주소를 찾아 이동하게 된다. 즉, urls.py에 작성한 name속성을 찾아가 이동한단말씀!
        # args는 여러값들을 리스트로 전달하는데 사용하는데 여기서는 pk값을 전달하도록 한다.
        return reverse('photo:photo_detail', args=[str(self.id)])

    # __str__은 photo클래스를 설명하는 문자열을 리턴한다.
    def __str__(self):
        return self.author.username+" " + self.created.strftime('%y-%m-%d %H:%M:%S')


#! on_delete의 종류
# CASCADE : 연결된 객체가 지워지면 해당 하위 객체도 같이 삭제된다.
# PROTECT : 말그대로 보호됨, 하위객채가 남아있다면 연결된 객체가 지워지지 않음
# SET_NULL : 연결된 객체만 삭제하고 필드값을 null로 설정한다
# SET_DEFAULT : 연결된 객체만 삭제하고 필드 값을 설정된 기본 값으로 변경
# SET() : 연결된 객채만 삭제하고 인자로 지정된 값으로 변경
# DO_NOTIONG : 아무것도 하지 않음

#! related_name의 역할은?
# 연결된 객체에서 하위객체의 목록을 부를때 사용하는 이름!

accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class RegisterFrom(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        # forms.ModelForm에게 상속받은 클래스에서 User테이블의 데이터 필드를 쉽게 지정할 수 있다..?
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterFrom

# Create your views here.


def register(request):
    # 회원정보가 POST를 통해 전달되었을때
    if request.method == 'POST':
        # 우리가 만든 forms.py의  RegisterFor을 POST로 받은 값의 유효성 검사를 진행하며 이상이 없으면 DB에 저장한다.
        user_form = RegisterFrom(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = RegisterFrom()
    return render(request, 'registration/register.html', {'form': user_form})

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Photo

# Create your views here.


class PhotoUploadView(CreateView):
    model = Photo
    fields = ['photo', 'text']
    # 업로드 할때 사용할 템플릿을 지정한다.
    template_name = 'photo/upload.html'

    # form_valid는 업로드가 끝난 뒤 이동할 페이지를 지정하기 위한 메서드
    def form_valid(self, form):
        # 작성자는 현재 로그인한 유저
        form.instance.author_id = self.request.user.id

        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'


# request는 함수형뷰의 기본 매개변수
# 함수형 뷰는 클래스 뷰와 달리 모든 기능을 직접 처리해야 한다.


def photo_list(request):
    # Photo 모델의 데이터를 전부 변수에 담는다.
    photos = Photo.objects.all()

    # 포토리스트에 접근했을때 템플릿과 변수에 담을 내용을 전달했다.
    return render(request, 'photo/list.html', {'photos': photos})

photo/templates/photo/delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html' %} {% block title %}- Delete{% endblock title %}
    <!-- 컨텐츠 시작 -->
    {% block content %}
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
          Do you want to delete {{object}}?
        </div>
        <form action="" method="POST">
          {{form.as_p}} {% csrf_token %}
          <input type="submit" class="btn btn-danger" value="Confirm" />
        </form>
      </div>
      <div class="col-md-2"></div>
    </div>
    {% endblock content %}
  </body>
</html>

photo/templates/photo/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html' %} {% block title %} {{object.text|truncatechars:10}}
    {% endblock title%} {% block content %}
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panel panel-default">
        <p>
          <img src="{{object.photo.url}}" style="width: 100%;" alt="" />
        </p>
        <button type="button" class="btn btn-outline-primary btn-sm">
          {{object.author.username}}
        </button>
        <p>{{object.text|linebreaksbr}}</p>
        <a
          href="{% url 'photo:photo_delete' pk=object.id %}"
          class="btn btn-outline-danger btn-sm float-right"
          >Delete</a
        >
        <a
          href="{% url 'photo:photo_update' pk=object.id %}"
          class="btn btn-outline-danger btn-sm float-right"
          >Update</a
        >
      </div>
      <div class="col-md-2"></div>
    </div>
    {% endblock content%}
  </body>
</html>

photo/templates/photo/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html' %} {% block title %}- List{% endblock title %}
    <!-- 컨텐츠 시작 -->
    {% block content %}
    <!-- photos라는 변수에 photo테이블의 데이터가 모두 담겨있다. -->
    {% for post in photos %}
    <!-- post 라는 변수애 각 데이터 1개를 담아 리스트를 뽑아내자~ -->
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panel panel-default">
        <p>
          <img
            src="{{post.photo.url}}"
            style="width: 100%;"
            alt="{{post.photo.url}}"
          />
        </p>
        <button class="btn btn-xs btn-info" type="button">
          {{post.author.username}}
        </button>
        <p>{{post.text|linebreaksbr}}</p>
        <p class="text-right">
          <a
            href="{% url 'photo:photo_detail' pk=post.id %}"
            class="btn btn-xs btn-success"
            >댓글달기</a
          >
        </p>
      </div>
      <div class="col-md-2"></div>
    </div>
    {% endfor %}
    <!-- ... -->
    {% endblock %}
  </body>
</html>

photo/templates/photo/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html' %} {% block title %}- Update{% endblock title %}
    <!-- 컨텐츠 시작 -->
    {%block content %}
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panel panel-default">
        <form action="" method="POST" enctype="multipart/form-data">
          {{form.as_p}} {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Update" />
        </form>
      </div>
      <div class="col-md-2"></div>
    </div>
    {% endblock content %}
  </body>
</html>

photo/templates/photo/upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <!-- base.html 확장하여 사용하기 설정 -->
    {% extends 'base.html' %} {% block title %}- Upload {% endblock title %}
    <!-- 컨텐츠 시작 -->
    {% block content %}
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panet panel-default">
        <!-- enctype는 method가 post일때만 사용가능한 옵션이다. -->
        <!-- application/x-www-form-urlencoded : 기본옵션 모든 문자열을 인코딩해 전달 -->
        <!-- multipart/form-data : 파일업로드 때 사용하는 옵션, 데이터를 문자열로 인코딩하지 않고 전달 -->
        <!-- text/plain : 뜨어쓰기만 '+'로 변환하고 특별한 인코딩 없이 전달 -->
        <form action="" method="post" enctype="multipart/form-data">
          {{form.as_p}} {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Upload" />
        </form>
      </div>
      <div class="col-md-2"></div>
    </div>
    {% endblock content %}
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
    />

    <!-- 부가적인 테마 -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"
    />

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <title>django stargram {% block title %} {% endblock title %}</title>
  </head>
  <body>
    <div class="container">
      <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a href="/" class="navbar-brand">django stargram</a>
          <ul class="nav">
            <li class="nav-item">
              <a href="/" class="activa nav-link">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="#" class="nav-link">Welcome,{{user.get_username}}</a>
            </li>
            <li class="nav-item">
              <!-- url은 urls.py의 'app_name : name' 으로 지정한다. -->
              <a href="{% url 'photo:photo_upload' %} class="nav-link"
                >Upload</a
              >
            </li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">SignUp</a></li>
            {% endif %}
          </ul>
        </nav>
      </header>

      {% block content %} {% endblock content %}
      <footer class="footer">
        <p>&copy; 2020 zuhwang.</p>
      </footer>
    </div>
  </body>
</html>